"""Add cantidad and unidad_medida_id to producto_ingrediente

Revision ID: ca7a9340ac99
Revises: 831cf6dc0995
Create Date: 2026-06-21 19:18:24.194035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ca7a9340ac99'
down_revision: Union[str, Sequence[str], None] = '831cf6dc0995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto_ingrediente', sa.Column('cantidad', sa.DECIMAL(precision=10, scale=3), server_default='1.000', nullable=False))
    op.add_column('producto_ingrediente', sa.Column('unidad_medida_id', sa.Integer(), server_default='2', nullable=False))
    op.create_foreign_key(None, 'producto_ingrediente', 'unidad_medida', ['unidad_medida_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'producto_ingrediente', type_='foreignkey')
    op.drop_column('producto_ingrediente', 'unidad_medida_id')
    op.drop_column('producto_ingrediente', 'cantidad')
    # ### end Alembic commands ###
